name: Latest Image

on:
    push:
        branches:
          - main

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build an push an image
              env:
                PACKAGER: ${{ secrets.PACKAGER }}
              run: |
                docker login --username Roaoch --password "$PACKAGER" ghcr.io
                DOCKER_BUILDKIT=1 docker build --secret id=NODE_AUTH_TOKEN,env=PACKAGER . --tag ghcr.io/eternal-encoders/urfunavigator-web:stable
                docker push ghcr.io/eternal-encoders/urfunavigator-web:stable